CREATE TABLE SBD_USER (
    ID NUMBER NOT NULL,
    USERNAME VARCHAR2(255) DEFAULT NULL,
    AGE NUMBER DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_U_U ON SBD_USER (USERNAME);

CREATE SEQUENCE SEQ_USER;